export const metadata = {
  title: "About Page",
  description: "Generated by create next app",
};

const about = () => {
  return <div className="text-center text-2xl"> About Page</div>;
};

export default about;
