export const metadata = {
  title: "Contact Page",
  description: "Generated by create next app",
};

const contact = () => {
  return <div className="text-center text-2xl"> Contact Page</div>;
};

export default contact;
