
import Link from "next/link";

export const metadata = {
  title: "Product Page",
  description: "Generated by create next app",
};

const ProductPage = () => {
  return (
    <>
      <div className="text-center text-2xl">Product Page</div>
      <ul className="flex gap-5 justify-center mt-96 bg-slate-400 text-zinc-800 text-3xl ">
        <li className="hover:text-green-400"><Link href="product/1">Product 1</Link></li>
        <li className="hover:text-green-400"><Link href="product/2">Product 2</Link></li>
        <li className="hover:text-green-400"><Link href="product/3">Product 3</Link></li>
        <li className="hover:text-green-400"><Link href="product/4">Product 4</Link></li>
        <li className="hover:text-green-400"><Link href="product/5">Product 5</Link></li>
        <li className="hover:text-green-400"><Link href="product/6">Product 6</Link></li>
        <li className="hover:text-green-400"><Link href="product/7">Product 7</Link></li>
        <li className="hover:text-green-400"><Link href="product/8">Product 8</Link></li>
        <li className="hover:text-green-400"><Link href="product/9">Product 9</Link></li>
      </ul>
    </>
  );
};

export default ProductPage;
