import Link from "next/link";

export const metadata = {
  title: "Blog Page",
  description: "Generated by create next app",
};

const blogPage = async () => {
  const res = await fetch(
    "http://headless.local/wp-json/wp/v2/posts?_embed"
  );
  const data = await res.json();
  return (
    <>
      <ul className="p-36">
        {data.map((post, index) => {
          return (
            <Link key={index} href={`blog/${post["slug"]}`}>
              <div className="cursor-pointer mb-10">
                <h3 className="font-medium mb-3 text-xl">
                  {" "}
                  {post["title"]["rendered"]}{" "}
                </h3>
                <div
                  className="text-gray-600"
                  dangerouslySetInnerHTML={{
                    __html: post["excerpt"]["rendered"],
                  }}
                ></div>
              </div>
            </Link>
          );
        })}
      </ul>
    </>
  );
};

export default blogPage;
