export const metadata = {
  title: "Product Page",
  description: "Generated by create next app",
};

const productId = ({ params }) => {
  return (
    <>
      <h1 className="text-center text-2xl">
        Product {params.productId} Content
      </h1>
    </>
  );
};

export default productId;
